Validation and Test Specs for Models 🎉 🚀 ✔️
Nizamuddin4493/blog_app pull request #3
Opened 2023-12-02 19:12 UTC by Nizamuddin4493

## Validation and Test Specs for Models 🎉 🚀 ✔️ 

- ### Used validations for the User model.
- ### Used validations for the Post model.
- ### Add unit specs for all of your models' methods and validations.

2023-12-02 19:38 UTC, fobadara requested changes
Hi @Nizamuddin4493,

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because it couldn't be done inline
[REQUIRED] Kindly fix the link to your license because it takes me to a 404 page


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 19:38 UTC, fobadara commented on spec/models/user_spec.rb
[REQUIRED] You are expected to test all custom methods. Kindly include tests for recent_posts

2023-12-02 19:38 UTC, fobadara commented on spec/models/post_spec.rb
[REQUIRED] You are expected to test all custom methods. Kindly include tests for update_user_posts_counter
 and recent_comments

2023-12-02 19:38 UTC, fobadara commented on spec/models/comment_spec.rb
[REQUIRED] You are expected to test all custom methods. Kindly include tests for update_posts_comments_counter

2023-12-02 19:38 UTC, fobadara commented on spec/models/like_spec.rb
[REQUIRED] You are expected to test all custom methods. Kindly include tests for update_posts_likes_counter

2023-12-02 20:45 UTC, KayLemba requested changes
Hi @Nizamuddin4493    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
Git flow is followed. ✔️
Professional README FILE

Required Changes ♻️
Check the comments under the review in the inline comments.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-02 20:45 UTC, KayLemba commented on spec/models/comment_spec.rb
> +      expect { create(:comment, post:, author: user) }.to change { post.reload.comments_counter }.by(1)
While you did a good job working on the project requirements I noticed some tests are failing it would be nice to correct the failing tests. Kindly look at the screenshot below:

 
![Screenshot 2023-12-02 at 10 42 50 PM](https://github.com/Nizamuddin4493/blog_app/assets/79506105/d5187b75-013c-4cb7-aba5-2c0c24c86a2e)

2023-12-07 08:50 UTC, Nizamuddin4493 commented
## Dear Code Reviewer, 👋 

I am pleased to inform you that all tests for the model using RSpec have been completed successfully, and there were no errors encountered during the testing process. The thorough testing has ensured that the model is functioning as expected. Please let me know if you have any questions or require further information.

Sincerely,
Nizamuddin Ahmadzai
![All tests passed](https://github.com/Nizamuddin4493/blog_app/assets/78977308/344dbd07-ca5a-4101-936b-800dc29ed69a)

2023-12-07 09:08 UTC, binhussen approved these changes
Hi @Nizamuddin4493 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/Nizamuddin4493/blog_app/assets/52010789/171fd29e-543d-4368-93b1-88838fbf7cff)

## Highlights
- Added Model Validation spec ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-07 10:37 UTC, merged